export TERM="xterm-256color"
source $HOME/antigen.zsh
export PATH="$HOME/.cargo/bin:$PATH"
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_TIME=fr_FR.UTF-8

# Personnal aliases
alias ll="ls -la --color=auto"

# POWERLEVEL9K environment variables
# POWERLEVEL9K_MODE='awesome-fontconfig'
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_INSTALLATION_PATH=$ANTIGEN_BUNDLES/bhilburn/powerlevel9k
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir virtualenv rbenv)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status vcs history time)

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

powerline-daemon -q
. ~/.local/lib/python3.5/site-packages/powerline/bindings/zsh/powerline.zsh
if [ -f ~/git/environment/setproxy_fn ]; then
        . ~/git/environment/setproxy_fn
fi

# If not running interactively, do not do anything
#[[ $- != *i* ]] && return
#if [[ -z "$TMUX" && -z "$(tmux ls | grep base)" ]]; then
#	exec tmux new -s base
#fi
#if [[ -z "$TMUX" ]]; then
#	exec tmux attach -t base
#fi

# Load the oh-my-zsh's library
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle gitignore
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting
# Extra zsh completions
antigen bundle zsh-users/zsh-completions
# Fish-like auto suggestions
antigen bundle zsh-users/zsh-autosuggestions
# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting
# powerlevel9k theme
antigen theme bhilburn/powerlevel9k powerlevel9k

# Tell antigen that you're done
antigen apply
